# List all the drivers
all: undirectedGraphtest

openhttest: undirectedGraphtest
	g++ -std=c++11 undirectedGraphtest.cpp -o undirectedGraphtest

# List all the executables under 'all:'
clean:
	rm *.o undirectedGraphtest
